RESOURCE_NAME = GetCurrentResourceName()

local VEHICLE_HANDLINGS = json.decode(LoadResourceFile(RESOURCE_NAME, 'data/vehicleHandlings.json'))
local COLLISION_DAMAGE_MULTIPLIER = tonumber(GetConvar('collisionDamageMultiplier', '4.0'))
local DEFORMATION_DAMAGE_MULTIPLIER = tonumber(GetConvar('deformationDamageMultiplier', '1.25'))
local ENGINE_DAMAGE_MULTIPLIER = tonumber(GetConvar('engineDamageMultiplier', '2.0'))
local DISABLE_RADAR = GetConvarInt('disableRadar', 1)
local DISABLE_RADIO = GetConvarInt('disableRadio', 0)
local MAX_ROLL = tonumber(GetConvar('maxRoll', '80.0'))
local PERSIST_STOLEN = GetConvarInt('persistStolen', 0)
local LANG = GetConvar('lang', 'en')

local vehiclesData = {}
local registeredFunctions = {}
local hasGpsCallback = function () return true end

local locale = nil
local localeFile = LoadResourceFile(RESOURCE_NAME, 'locale/'.. LANG ..'.json')
if localeFile then
    locale = json.decode(localeFile)
else
    locale = json.decode(LoadResourceFile(RESOURCE_NAME, 'locale/en.json'))
end

local flagsIndex = {
    withPolice = 0,
    withNotAutoGenerated = 1,
    hasPedInside = 2,
    hasPlayerInside = 4,
    exclusivelyPolice = 10,
    heli = 12,
    boat = 13,
    plane = 14,
    isBusy = 16,
    trailer = 17,
    blimp = 18,
}
local allFlags = {
    withPolice = 1 << flagsIndex.withPolice, -- 0x00001
    withNotAutoGenerated = 1 << flagsIndex.withNotAutoGenerated, -- 0x00002
    hasPedInside = 1 << flagsIndex.hasPedInside, -- 0x00004
    hasPlayerInside = 1 << flagsIndex.hasPlayerInside, -- 0x00010
    exclusivelyPolice = 1 << flagsIndex.exclusivelyPolice, -- 0x00400
    heli = 1 << flagsIndex.heli, -- 0x01000
    boat = 1 << flagsIndex.boat, -- 0x02000
    plane = 1 << flagsIndex.plane, -- 0x04000
    isBusy = 1 << flagsIndex.isBusy, -- 0x10000
    trailer = 1 << flagsIndex.trailer, -- 0x20000
    blimp = 1 << flagsIndex.blimp, -- 0x40000
}
local allVehicles = {
    notFlyingVehicles = {
        withPolice = true,
        withNotAutoGenerated = true,
        hasPedInside = true,
        hasPlayerInside = true,
        isBusy = true,
        trailer = true,
    },
    flyingVehicles = {
        withPolice = true,
        withNotAutoGenerated = true,
        hasPedInside = true,
        hasPlayerInside = true,
        heli = true,
        plane = true,
        isBusy = true,
        blimp = true,
    },
    boatVehicles = {
        withPolice = true,
        withNotAutoGenerated = true,
        hasPedInside = true,
        hasPlayerInside = true,
        boat = true,
        isBusy = true,
    },
}

AddEventHandler('onClientResourceStart', function (resource)
    if resource == RESOURCE_NAME then
        TriggerServerEvent('vehicle:data:init')
        repeat Wait(100) until IsMinimapRendering()
        if DISABLE_RADAR then
            log.debug("Disabling radar...")
            DisplayRadar(false)
        end
    end
end)

AddEventHandler('gameEventTriggered', function (name, data)
    if name == 'CEventNetworkPlayerEnteredVehicle' then
        local player, vehicle = table.unpack(data)
        if player == PlayerId() then
            TriggerEvent('vehicle:player:entered', vehicle)
        end
    end
end)

AddEventHandler('vehicle:player:entered', function (vehicle)
    local playerPed = PlayerPedId()
    local model = GetEntityModel(vehicle)
    if PERSIST_STOLEN and not IsEntityAMissionEntity(vehicle) then
        SetEntityAsMissionEntity(vehicle, true, true)
    end
    for _, veh in pairs(VEHICLE_HANDLINGS) do
        if GetHashKey(veh['Id']) == GetDisplayNameFromVehicleModel(model) then
            local fCollisionDamageMult = tonumber(string.format("%.2f", GetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fCollisionDamageMult')))
            local fDeformationDamageMult = tonumber(string.format("%.2f", GetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fDeformationDamageMult')))
            local fEngineDamageMult = tonumber(string.format("%.2f", GetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fEngineDamageMult')))
            if 
                veh['CollisionDamageMult'] == fCollisionDamageMult
                and veh['DeformationDamageMult'] == fDeformationDamageMult
                and veh['EngineDamageMult'] == fEngineDamageMult
            then
                SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fCollisionDamageMult', fCollisionDamageMult * COLLISION_DAMAGE_MULTIPLIER)
                SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fDeformationDamageMult', fDeformationDamageMult * DEFORMATION_DAMAGE_MULTIPLIER)
                SetVehicleHandlingFloat(vehicle, 'CHandlingData', 'fEngineDamageMult', fEngineDamageMult * ENGINE_DAMAGE_MULTIPLIER)
            end
        end
    end
    RollUpWindow(vehicle, 0)
    RollUpWindow(vehicle, 1)
    if DISABLE_RADAR and hasGps() then
        DisplayRadar(true)
    end
    SetVehicleRadioEnabled(vehicle, not DISABLE_RADIO)
    for name, vehFunction in pairs(registeredFunctions) do
        if vehFunction.entered then
            registeredFunctions[name].data = vehFunction.entered(vehicle, registeredFunctions[name].data)
        end
    end
    CreateThread(function ()
        while true do
            local roll = GetEntityRoll(vehicle)
            if not IsPedInAnyVehicle(playerPed) or not DoesEntityExist(vehicle) then
                if DISABLE_RADAR and not IsRadarHidden() then
                    DisplayRadar(false)
                end
                for name, vehFunction in pairs(registeredFunctions) do
                    if vehFunction.exited then
                        registeredFunctions[name].data = vehFunction.exited(vehicle, registeredFunctions[name].data)
                    end
                end
                TriggerEvent('vehicle:player:left', vehicle)
                return
            end
            if GetPedInVehicleSeat(vehicle, -1) == playerPed
                and (IsEntityInAir(vehicle) or roll > MAX_ROLL or roll < -MAX_ROLL)
                and not IsThisModelABoat(model)
                and not IsThisModelAHeli(model)
                and not IsThisModelAJetski(model)
                and not IsThisModelAPlane(model)
            then
                DisableControlAction(0, 59, true)
                DisableControlAction(0, 60, true)
            end
            for name, vehFunction in pairs(registeredFunctions) do
                if vehFunction.looped then
                    registeredFunctions[name].data = vehFunction.looped(vehicle, registeredFunctions[name].data)
                end
            end
            Wait(0)
        end
    end)
end)

RegisterNetEvent('vehicle:data:sync')
AddEventHandler('vehicle:data:sync', function (vehicles)
    vehiclesData = vehicles
    TriggerEvent('vehicle:data:synced', vehiclesData)
end)

function registerFunction(name, data, entered, looped, exited)
    if not registeredFunctions[name] then
        registeredFunctions[name] = {
            data = data,
            entered = entered,
            looped = looped,
            exited = exited
        }
    end
end

function registerHasGps(callback)
    hasGpsCallback = callback
end

function getSyncedData(vehicle)
    if vehiclesData[VehToNet(vehicle)] then
        return vehiclesData[VehToNet(vehicle)]
    end
    return nil
end

function getLocale()
    return locale
end

function getVehicleAhead(options)
    if not options then
        options = {}
    end
    if not options.radius then
        options.radius = 2.75
    end
    if not options.distance then
        options.distance = 1.66
    end
    if not options.model then
        options.model = 0
    else
        if type(options.model) == 'string' then
            options.model = GetHashKey(options.model)
        end
    end
    if not options.position then
        local playerPed = PlayerPedId()
        options.position = GetEntityCoords(playerPed) + GetEntityForwardVector(playerPed) * options.distance
    end
    for _, vehicles in pairs(allVehicles) do
        local flag = 0
        for name, state in pairs(vehicles) do
            if state and allFlags[name] then
                flag = flag | allFlags[name]
            end
        end
        if IsAnyVehicleNearPoint(options.position, options.radius) then
            local vehicle = GetClosestVehicle(options.position.x, options.position.y, options.position.z, options.radius, options.model, flag)
            if DoesEntityExist(vehicle) then
                return vehicle
            end
        end
    end
    return nil
end

function getVehicleFromNetId(netId, force)
    if NetworkDoesNetworkIdExist(netId) then
        local vehicle = NetToVeh(netId)
        if force or GetPedInVehicleSeat(vehicle, -1) ~= PlayerPedId() then
            return vehicle
        end
    end
    return nil
end

function hasGps()
    return hasGpsCallback()
end
